# Generated by Django 4.1.6 on 2023-02-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_pettycashtransaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashtransaction',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
