# Generated by Django 4.1.6 on 2023-02-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_pettycashtransaction_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='receipt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
